# Generated by Django 6.0.2 on 2026-02-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_address_city_alter_address_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='emi_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='emi_months',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
